### ISSUE TITLE
Clonable seems abandoned -> use httrack instead

### ISSUE THREAD

**Issue by freenerd** [CloneableApp/Cloneable#3]
For everyone else who ends up here, because the website is great and SEO works well, but then runs into problems during installation (see #2)

Use [httrack](https://www.httrack.com/) instead, it works:
```
brew install httrack
httrack
```

**Comment by ChrisMoutsos** [comment]
Hi,

I responded to #2 with some guidance and added some steps to the README to remind users to use the correct Node version (currently v16.13.1).

If you are having a specific problem with installation, please open a new issue with details, or use #2 if appropriate.

---

Using HTTrack is always an option, but shortcomings with it are one of the reasons I made Cloneable. But if HTTrack works for your use case, great. In general, if a user is having trouble installing and running a custom software from source, like Cloneable, I'd recommend just using something with pre-built binaries like HTTrack.
